/* ─────────────────────────  재료 시세표  ─────────────────────────
   pq = 파는 단위 수량, p = 그 단위 가격(원), s = 냉장 보관 가능 일수      */
const ING = {
  rice:{n:'쌀',u:'g',pl:'4kg',pq:4000,p:15900,a:'쌀·면·간편',s:365,d:'grain'},
  somyeon:{n:'소면',u:'g',pl:'900g',pq:900,p:3480,a:'쌀·면·간편',s:365,d:'grain'},
  spaghetti:{n:'스파게티면',u:'g',pl:'500g',pq:500,p:3290,a:'쌀·면·간편',s:365,d:'grain'},
  udon:{n:'생우동면',u:'g',pl:'2인분 400g',pq:400,p:3180,a:'쌀·면·간편',s:30,d:'grain'},
  tortilla:{n:'또띠아',u:'g',pl:'8장 320g',pq:320,p:3980,a:'쌀·면·간편',s:30,d:'grain'},
  bread:{n:'식빵',u:'g',pl:'1봉 420g',pq:420,p:2880,a:'쌀·면·간편',s:5,d:'grain'},
  tteok:{n:'떡볶이·떡국떡',u:'g',pl:'500g',pq:500,p:3980,a:'쌀·면·간편',s:14,d:'grain'},
  miyeok:{n:'건미역',u:'g',pl:'50g',pq:50,p:3480,a:'쌀·면·간편',s:365,d:'veg'},

  porkbelly:{n:'삼겹살',u:'g',pl:'500g',pq:500,p:12900,a:'정육',s:3,d:'meat-pork'},
  pork:{n:'돼지 앞다리살',u:'g',pl:'500g',pq:500,p:6900,a:'정육',s:3,d:'meat-pork'},
  porkground:{n:'돼지 다짐육',u:'g',pl:'400g',pq:400,p:6480,a:'정육',s:2,d:'meat-pork'},
  beef:{n:'소불고기용',u:'g',pl:'400g',pq:400,p:13900,a:'정육',s:3,d:'meat-beef'},
  chickenleg:{n:'닭다리살',u:'g',pl:'500g',pq:500,p:7900,a:'정육',s:3,d:'meat-chicken'},
  chickenbreast:{n:'닭가슴살',u:'g',pl:'500g',pq:500,p:6900,a:'정육',s:3,d:'meat-chicken'},
  bacon:{n:'베이컨',u:'g',pl:'200g',pq:200,p:4480,a:'유제품·냉장',s:14,d:'meat-pork'},
  ham:{n:'햄',u:'g',pl:'200g',pq:200,p:3980,a:'가공·양념',s:180,d:'meat-pork'},

  squid:{n:'오징어',u:'g',pl:'1마리 250g',pq:250,p:4980,a:'수산',s:2,d:'fish'},
  mackerel:{n:'손질 고등어',u:'g',pl:'2손 400g',pq:400,p:5980,a:'수산',s:2,d:'fish'},
  anchovy:{n:'국물용 멸치',u:'g',pl:'200g',pq:200,p:5900,a:'수산',s:180,d:'fish'},
  tunacan:{n:'참치캔',u:'g',pl:'100g×3',pq:300,p:5480,a:'가공·양념',s:365,d:'fish'},
  shrimp:{n:'냉동 새우살',u:'g',pl:'300g',pq:300,p:8900,a:'수산',s:90,d:'fish'},
  gim:{n:'구운 김',u:'장',pl:'10봉 30장',pq:30,p:3500,a:'가공·양념',s:180,d:'veg'},

  onion:{n:'양파',u:'g',pl:'1.5kg 망',pq:1500,p:3980,a:'농산',s:30,d:'veg'},
  potato:{n:'감자',u:'g',pl:'1kg',pq:1000,p:3480,a:'농산',s:30,d:'veg'},
  carrot:{n:'당근',u:'g',pl:'500g',pq:500,p:2280,a:'농산',s:21,d:'veg'},
  zucchini:{n:'애호박',u:'g',pl:'1개 250g',pq:250,p:1980,a:'농산',s:7,d:'veg'},
  greenonion:{n:'대파',u:'g',pl:'1단 700g',pq:700,p:3480,a:'농산',s:10,d:'veg'},
  cabbage:{n:'양배추',u:'g',pl:'1/2통 600g',pq:600,p:2980,a:'농산',s:14,d:'veg'},
  kimchi:{n:'배추김치',u:'g',pl:'1kg',pq:1000,p:8900,a:'유제품·냉장',s:60,d:'veg'},
  beansprout:{n:'콩나물',u:'g',pl:'300g',pq:300,p:1780,a:'농산',s:4,d:'veg'},
  spinach:{n:'시금치',u:'g',pl:'200g',pq:200,p:2480,a:'농산',s:4,d:'veg'},
  mushroom:{n:'새송이버섯',u:'g',pl:'300g',pq:300,p:2480,a:'농산',s:10,d:'veg'},
  tomato:{n:'토마토',u:'g',pl:'700g',pq:700,p:5480,a:'농산',s:7,d:'veg'},
  paprika:{n:'파프리카',u:'g',pl:'2개 400g',pq:400,p:3180,a:'농산',s:10,d:'veg'},
  cucumber:{n:'오이',u:'g',pl:'2개 400g',pq:400,p:2480,a:'농산',s:7,d:'veg'},
  radish:{n:'무',u:'g',pl:'1개 800g',pq:800,p:2680,a:'농산',s:21,d:'veg'},
  lettuce:{n:'상추',u:'g',pl:'150g',pq:150,p:2180,a:'농산',s:4,d:'veg'},
  chili:{n:'청양고추',u:'g',pl:'100g',pq:100,p:1980,a:'농산',s:10,d:'veg'},
  broccoli:{n:'브로콜리',u:'g',pl:'1개 300g',pq:300,p:2480,a:'농산',s:7,d:'veg'},
  corn:{n:'옥수수콘 캔',u:'g',pl:'340g',pq:340,p:2480,a:'가공·양념',s:365,d:'veg'},

  egg:{n:'계란',u:'개',pl:'10구',pq:10,p:4280,a:'유제품·냉장',s:21,d:'egg'},
  tofu:{n:'두부',u:'g',pl:'300g',pq:300,p:2180,a:'유제품·냉장',s:10,d:'veg'},
  milk:{n:'우유',u:'ml',pl:'900ml',pq:900,p:3180,a:'유제품·냉장',s:10,d:'dairy'},
  cheese:{n:'슬라이스 치즈',u:'장',pl:'10장',pq:10,p:5480,a:'유제품·냉장',s:30,d:'dairy'},
  mozz:{n:'모짜렐라 치즈',u:'g',pl:'500g',pq:500,p:8900,a:'유제품·냉장',s:21,d:'dairy'},
  butter:{n:'버터',u:'g',pl:'200g',pq:200,p:5980,a:'유제품·냉장',s:90,d:'dairy'},
  cream:{n:'생크림',u:'ml',pl:'200ml',pq:200,p:3480,a:'유제품·냉장',s:14,d:'dairy'},

  soysauce:{n:'간장',u:'ml',pl:'500ml',pq:500,p:4280,a:'가공·양념',s:365,d:'veg'},
  gochujang:{n:'고추장',u:'g',pl:'500g',pq:500,p:5980,a:'가공·양념',s:365,d:'veg'},
  gochugaru:{n:'고춧가루',u:'g',pl:'200g',pq:200,p:6900,a:'가공·양념',s:180,d:'veg'},
  doenjang:{n:'된장',u:'g',pl:'500g',pq:500,p:5480,a:'가공·양념',s:365,d:'veg'},
  garlic:{n:'다진마늘',u:'g',pl:'200g',pq:200,p:2980,a:'농산',s:30,d:'veg'},
  sesameoil:{n:'참기름',u:'ml',pl:'160ml',pq:160,p:6480,a:'가공·양념',s:365,d:'veg'},
  oil:{n:'식용유',u:'ml',pl:'900ml',pq:900,p:4980,a:'가공·양념',s:365,d:'veg'},
  sugar:{n:'설탕',u:'g',pl:'1kg',pq:1000,p:2480,a:'가공·양념',s:365,d:'veg'},
  salt:{n:'소금',u:'g',pl:'1kg',pq:1000,p:2180,a:'가공·양념',s:365,d:'veg'},
  pepper:{n:'후춧가루',u:'g',pl:'50g',pq:50,p:3480,a:'가공·양념',s:365,d:'veg'},
  vinegar:{n:'식초',u:'ml',pl:'500ml',pq:500,p:2280,a:'가공·양념',s:365,d:'veg'},
  mirin:{n:'맛술',u:'ml',pl:'500ml',pq:500,p:3280,a:'가공·양념',s:365,d:'veg'},
  ketchup:{n:'케첩',u:'g',pl:'300g',pq:300,p:2980,a:'가공·양념',s:365,d:'veg'},
  mayo:{n:'마요네즈',u:'g',pl:'300g',pq:300,p:3480,a:'가공·양념',s:365,d:'veg'},
  oyster:{n:'굴소스',u:'g',pl:'250g',pq:250,p:4180,a:'가공·양념',s:365,d:'fish'},
  curry:{n:'카레가루',u:'g',pl:'100g',pq:100,p:2180,a:'가공·양념',s:365,d:'veg'},
  tomatosauce:{n:'토마토 파스타소스',u:'g',pl:'600g',pq:600,p:4480,a:'가공·양념',s:365,d:'veg'},
  starch:{n:'전분가루',u:'g',pl:'400g',pq:400,p:2480,a:'가공·양념',s:365,d:'veg'},
  flour:{n:'밀가루',u:'g',pl:'1kg',pq:1000,p:2180,a:'가공·양념',s:365,d:'veg'}
};
const AISLES = ['농산','정육','수산','유제품·냉장','가공·양념','쌀·면·간편'];
const FRESH_AISLES = new Set(['농산','정육','수산']);

const TOOLS = [
  {id:'pot',n:'냄비',def:true},{id:'pan',n:'프라이팬',def:true},{id:'knife',n:'칼·도마',def:true},
  {id:'rice',n:'밥솥',def:true},{id:'micro',n:'전자레인지',def:true},{id:'air',n:'에어프라이어',def:true},
  {id:'oven',n:'오븐',def:false},{id:'blender',n:'믹서',def:false}
];
const CUISINES = ['한식','양식','일식','중식'];
const PANTRY = [
  {id:'p0',n:'쌀',ids:['rice'],def:true},
  {id:'p1',n:'간장·소금·설탕·후추',ids:['soysauce','salt','sugar','pepper'],def:true},
  {id:'p2',n:'식용유·참기름',ids:['oil','sesameoil'],def:true},
  {id:'p3',n:'고추장·된장·고춧가루',ids:['gochujang','doenjang','gochugaru'],def:false},
  {id:'p4',n:'다진마늘',ids:['garlic'],def:false},
  {id:'p5',n:'케첩·마요·굴소스',ids:['ketchup','mayo','oyster'],def:false},
  {id:'p6',n:'밀가루·전분·식초·맛술',ids:['flour','starch','vinegar','mirin'],def:false}
];

/* ─────────────────────────  레시피 (1인 1끼 기준)  ───────────────────────── */
const R = [
 {id:'kbb',n:'김치볶음밥',c:'한식',t:15,sp:1,q:1,tools:['pan',['rice','pot','micro']],
  ing:{rice:100,kimchi:100,egg:1,ham:40,greenonion:20,oil:10,sesameoil:5},
  steps:['김치와 햄을 잘게 썰어 기름에 볶아 신맛을 날린다.','밥을 넣고 눌러가며 볶다가 대파를 넣는다.','참기름 두르고 계란프라이를 얹는다.']},
 {id:'dwj',n:'된장찌개',c:'한식',t:25,sp:1,q:0,tools:['pot','knife',['rice','pot']],
  ing:{rice:100,tofu:100,zucchini:60,onion:50,potato:60,doenjang:25,garlic:5,greenonion:15,anchovy:8},
  steps:['멸치를 넣고 물 400ml를 10분 끓여 육수를 낸다.','된장을 풀고 감자·양파를 먼저, 애호박·두부를 나중에 넣는다.','마늘과 대파를 넣고 2분 더 끓인다.']},
 {id:'kcj',n:'김치찌개',c:'한식',t:30,sp:2,q:0,tools:['pot','knife',['rice','pot']],
  ing:{rice:100,kimchi:150,pork:80,tofu:80,onion:40,greenonion:15,gochugaru:5,garlic:5},
  steps:['앞다리살을 기름 없이 볶아 겉면을 익힌다.','김치를 넣고 같이 볶다가 물 350ml를 붓는다.','15분 끓인 뒤 두부·대파를 넣고 고춧가루로 색을 낸다.']},
 {id:'jyk',n:'제육볶음',c:'한식',t:25,sp:2,q:0,tools:['pan','knife',['rice','pot']],
  ing:{rice:100,pork:150,onion:60,greenonion:20,gochujang:25,gochugaru:5,soysauce:10,sugar:8,garlic:5,oil:10},
  steps:['고추장·고춧가루·간장·설탕·마늘을 섞어 양념장을 만든다.','고기에 양념을 버무려 10분 재운다.','센 불에 양파와 함께 볶고 마지막에 대파를 넣는다.']},
 {id:'gml',n:'계란말이 백반',c:'한식',t:15,sp:0,q:1,tools:['pan',['rice','pot','micro']],
  ing:{rice:100,egg:3,carrot:20,greenonion:10,salt:2,oil:8,gim:2},
  steps:['계란에 잘게 썬 당근·대파·소금을 섞는다.','약불 팬에 얇게 부어 반쯤 익으면 말기를 세 번 반복한다.','한 김 식혀 썰고 밥·김과 함께 낸다.']},
 {id:'kng',n:'콩나물국밥',c:'한식',t:20,sp:1,q:1,tools:['pot',['rice','pot','micro']],
  ing:{rice:100,beansprout:120,anchovy:8,greenonion:15,garlic:5,gochugaru:3,egg:1},
  steps:['멸치 육수 400ml에 콩나물을 넣고 뚜껑 덮은 채 5분 끓인다.','밥을 넣고 한소끔 끓여 마늘·고춧가루로 간을 맞춘다.','불을 끄고 계란을 풀어 얹은 뒤 대파를 뿌린다.']},
 {id:'blg',n:'소불고기',c:'한식',t:25,sp:0,q:0,tools:['pan','knife',['rice','pot']],
  ing:{rice:100,beef:150,onion:60,carrot:30,greenonion:15,soysauce:25,sugar:10,sesameoil:5,garlic:5},
  steps:['간장·설탕·마늘·참기름에 고기를 15분 재운다.','팬을 달궈 고기를 먼저 펴 굽는다.','양파·당근을 넣고 국물이 자작해질 때까지 볶는다.']},
 {id:'gdo',n:'고등어구이',c:'한식',t:20,sp:0,q:1,tools:[['air','pan'],['rice','pot','micro']],
  ing:{rice:100,mackerel:200,salt:3,kimchi:50},
  steps:['고등어 물기를 닦고 소금을 뿌려 10분 둔다.','에어프라이어 190도 12분, 뒤집지 않고 굽는다.','밥·김치와 함께 낸다.']},
 {id:'bbb',n:'비빔밥',c:'한식',t:30,sp:1,q:0,tools:['pan','knife',['rice','pot']],
  ing:{rice:100,beansprout:60,spinach:60,carrot:40,zucchini:50,egg:1,gochujang:25,sesameoil:8},
  steps:['콩나물·시금치는 데쳐 참기름·소금에 무친다.','당근과 애호박은 채 썰어 각각 볶는다.','밥 위에 돌려 담고 계란프라이와 고추장을 올린다.']},
 {id:'jch',n:'잔치국수',c:'한식',t:20,sp:0,q:1,tools:['pot',['pot']],
  ing:{somyeon:100,anchovy:10,zucchini:40,egg:1,greenonion:15,soysauce:15,gim:2},
  steps:['멸치 육수 500ml를 내고 간장으로 간한다.','소면은 따로 삶아 찬물에 헹궈 사린다.','애호박볶음·지단·김을 고명으로 올린다.']},
 {id:'tgk',n:'떡국',c:'한식',t:20,sp:0,q:1,tools:['pot'],
  ing:{tteok:180,egg:1,gim:2,greenonion:15,anchovy:8,soysauce:10},
  steps:['떡은 찬물에 10분 담가 둔다.','멸치 육수에 떡을 넣고 떠오를 때까지 끓인다.','계란을 풀어 넣고 김·대파를 올린다.']},
 {id:'dbj',n:'두부조림',c:'한식',t:20,sp:1,q:1,tools:['pan',['rice','pot','micro']],
  ing:{rice:100,tofu:200,soysauce:20,gochugaru:5,greenonion:15,garlic:5,sugar:5,oil:10},
  steps:['두부를 도톰하게 썰어 앞뒤로 노릇하게 지진다.','간장·고춧가루·마늘·설탕에 물 60ml를 섞어 붓는다.','국물을 끼얹어가며 조리고 대파를 뿌린다.']},
 {id:'ojb',n:'오징어볶음',c:'한식',t:25,sp:3,q:0,tools:['pan','knife',['rice','pot']],
  ing:{rice:100,squid:200,onion:60,cabbage:80,greenonion:20,gochujang:20,gochugaru:6,sugar:8,garlic:5},
  steps:['오징어는 칼집을 넣어 한입 크기로 썬다.','센 불에 채소를 먼저 볶다가 오징어를 넣는다.','양념을 넣고 3분 안에 빠르게 볶아낸다.']},
 {id:'dkj',n:'닭다리 감자조림',c:'한식',t:35,sp:2,q:0,tools:['pot','knife',['rice','pot']],
  ing:{rice:100,chickenleg:200,potato:120,carrot:50,onion:60,gochujang:20,gochugaru:8,soysauce:20,garlic:5},
  steps:['닭다리살을 데치듯 한 번 볶아 기름을 뺀다.','양념과 물 300ml를 붓고 감자·당근을 넣는다.','뚜껑 덮고 20분, 국물이 반으로 줄 때까지 조린다.']},
 {id:'myg',n:'소고기 미역국',c:'한식',t:30,sp:0,q:0,tools:['pot',['rice','pot']],
  ing:{rice:100,miyeok:8,beef:60,soysauce:10,sesameoil:5,garlic:3},
  steps:['미역을 20분 불려 헹구고 한입 크기로 자른다.','참기름에 고기와 미역을 5분 볶는다.','물 500ml를 붓고 15분 끓여 간장·마늘로 간한다.']},
 {id:'sgs',n:'삼겹살 쌈밥',c:'한식',t:20,sp:0,q:1,tools:[['pan','air'],['rice','pot']],
  ing:{rice:100,porkbelly:180,lettuce:60,garlic:5,kimchi:60,doenjang:10,gochujang:5},
  steps:['팬을 충분히 달군 뒤 삼겹살을 올려 건드리지 않고 굽는다.','기름이 나오면 김치를 옆에서 같이 굽는다.','된장·고추장을 섞어 쌈장을 만들어 상추에 싼다.']},
 {id:'smg',n:'소고기 무국',c:'한식',t:30,sp:0,q:0,tools:['pot','knife',['rice','pot']],
  ing:{rice:100,beef:80,radish:150,greenonion:15,soysauce:15,garlic:5,sesameoil:5},
  steps:['무를 나박하게 썰어 참기름에 고기와 볶는다.','무가 투명해지면 물 500ml를 붓는다.','15분 끓여 간장·마늘로 간하고 대파를 넣는다.']},
 {id:'tbk',n:'떡볶이',c:'한식',t:20,sp:2,q:1,tools:['pot'],
  ing:{tteok:200,gochujang:25,gochugaru:8,sugar:15,greenonion:20,cabbage:50,ham:40,egg:1},
  steps:['물 300ml에 고추장·고춧가루·설탕을 풀어 끓인다.','떡과 양배추·햄을 넣고 중불에서 졸인다.','삶은 계란과 대파를 올린다.']},
 {id:'kcj2',n:'김치전',c:'한식',t:20,sp:1,q:1,tools:['pan'],
  ing:{flour:80,kimchi:120,egg:1,greenonion:20,oil:20,chili:5},
  steps:['김치를 잘게 썰어 밀가루·계란·물 80ml와 섞는다.','기름을 넉넉히 두른 팬에 얇게 편다.','한 면이 바삭해지면 뒤집어 눌러가며 굽는다.']},
 {id:'bbg',n:'비빔국수',c:'한식',t:15,sp:2,q:1,tools:['pot','knife'],
  ing:{somyeon:100,cucumber:60,kimchi:60,gochujang:20,vinegar:10,sugar:8,sesameoil:5,egg:1,lettuce:30},
  steps:['고추장·식초·설탕·참기름을 섞어 양념장을 만든다.','소면을 삶아 찬물에 여러 번 헹궈 물기를 뺀다.','채 썬 오이·상추·김치와 함께 비비고 삶은 계란을 올린다.']},

 {id:'tps',n:'토마토 파스타',c:'양식',t:25,sp:0,q:0,tools:['pot','pan'],
  ing:{spaghetti:100,tomatosauce:150,onion:50,bacon:40,garlic:5,oil:10,cheese:1},
  steps:['면을 소금 넣은 물에 8분 삶고 면수 100ml를 남긴다.','베이컨과 양파·마늘을 볶다가 소스를 붓는다.','면과 면수를 넣어 1분 볶고 치즈를 올린다.']},
 {id:'cps',n:'크림 파스타',c:'양식',t:25,sp:0,q:0,tools:['pot','pan'],
  ing:{spaghetti:100,cream:100,milk:50,bacon:40,mushroom:60,garlic:5,pepper:1},
  steps:['면을 8분 삶는다.','베이컨·버섯·마늘을 볶고 생크림과 우유를 붓는다.','면을 넣고 소스가 감길 때까지 졸인 뒤 후추를 넉넉히.']},
 {id:'aoo',n:'알리오 올리오',c:'양식',t:20,sp:1,q:1,tools:['pot','pan'],
  ing:{spaghetti:100,garlic:15,chili:10,oil:20,salt:3},
  steps:['마늘을 약불 기름에 천천히 볶아 향을 낸다.','청양고추를 넣고 면수 100ml를 부어 유화시킨다.','삶은 면을 넣고 세게 흔들어 섞는다.']},
 {id:'omr',n:'오므라이스',c:'양식',t:25,sp:0,q:0,tools:['pan',['rice','pot','micro']],
  ing:{rice:100,egg:2,onion:50,carrot:30,ham:50,ketchup:30,corn:30},
  steps:['양파·당근·햄을 잘게 볶다가 밥과 케첩을 넣어 볶는다.','계란을 풀어 약불에서 얇게 부친다.','볶음밥을 감싸 접시에 뒤집어 담는다.']},
 {id:'cst',n:'치킨 스테이크와 구운 채소',c:'양식',t:30,sp:0,q:0,tools:[['air','pan','oven'],'knife'],
  ing:{chickenleg:200,paprika:60,broccoli:60,potato:100,salt:3,pepper:1,oil:10},
  steps:['닭다리살에 소금·후추를 뿌려 15분 둔다.','채소는 한입 크기로 썰어 기름에 버무린다.','에어프라이어 200도에서 닭 15분, 채소 10분 굽는다.']},
 {id:'psp',n:'감자 수프',c:'양식',t:30,sp:0,q:0,tools:['pot','blender'],
  ing:{potato:200,onion:50,milk:150,butter:15,salt:3,bread:60},
  steps:['버터에 양파를 볶다가 얇게 썬 감자를 넣는다.','물 200ml를 붓고 감자가 으깨질 때까지 끓인다.','우유를 넣고 갈아서 소금 간, 식빵을 구워 곁들인다.']},
 {id:'gsw',n:'그릴 샌드위치',c:'양식',t:12,sp:0,q:1,tools:['pan'],
  ing:{bread:90,egg:1,cheese:1,ham:40,cabbage:50,mayo:15,ketchup:10},
  steps:['양배추를 채 썰어 마요네즈에 버무린다.','계란과 햄을 팬에 굽고 빵도 같이 굽는다.','치즈-계란-양배추 순으로 쌓아 눌러 반으로 자른다.']},
 {id:'brt',n:'부리또 볼',c:'양식',t:25,sp:1,q:0,tools:['pan','knife'],
  ing:{tortilla:80,porkground:120,cabbage:60,tomato:60,mozz:30,ketchup:20,corn:30},
  steps:['다짐육을 소금·후추로 볶는다.','또띠아를 마른 팬에 데운다.','채 썬 양배추·토마토·옥수수·치즈와 함께 싼다.']},
 {id:'sps',n:'마늘버터 새우 파스타',c:'양식',t:25,sp:1,q:0,tools:['pot','pan'],
  ing:{spaghetti:100,shrimp:100,garlic:15,butter:20,chili:5,salt:3},
  steps:['새우는 해동해 물기를 닦는다.','버터에 마늘·고추를 볶고 새우를 넣어 겉만 익힌다.','면과 면수 100ml를 넣고 재빨리 섞는다.']},
 {id:'grt',n:'감자 그라탕',c:'양식',t:40,sp:0,q:0,tools:[['oven','air'],'pot'],
  ing:{potato:150,milk:120,mozz:60,bacon:40,onion:40,butter:15},
  steps:['감자를 얇게 썰어 우유에 넣고 5분 삶는다.','내열용기에 감자·베이컨·양파를 켜켜이 담는다.','치즈를 덮어 200도에서 15분, 윗면이 노릇해질 때까지.']},

 {id:'gyd',n:'규동',c:'일식',t:20,sp:0,q:1,tools:['pan',['rice','pot']],
  ing:{rice:130,beef:130,onion:80,soysauce:25,sugar:10,mirin:15,egg:1},
  steps:['간장·설탕·맛술·물 100ml를 끓인다.','양파를 넣어 숨을 죽이고 고기를 펴 넣는다.','계란을 반만 풀어 둘러 얹고 뚜껑을 덮어 1분.']},
 {id:'udn',n:'가케 우동',c:'일식',t:15,sp:0,q:1,tools:['pot'],
  ing:{udon:200,anchovy:10,soysauce:20,greenonion:15,egg:1,gim:2},
  steps:['멸치 육수 500ml에 간장으로 간을 한다.','우동면을 끓는 물에 1분 데쳐 그릇에 담는다.','국물을 붓고 반숙 계란·김·대파를 올린다.']},
 {id:'crr',n:'카레라이스',c:'일식',t:35,sp:1,q:0,tools:['pot','knife',['rice','pot']],
  ing:{rice:130,curry:40,potato:120,carrot:60,onion:80,pork:100},
  steps:['고기와 양파를 볶다가 감자·당근을 넣는다.','물 400ml를 붓고 채소가 익을 때까지 끓인다.','불을 줄이고 카레가루를 풀어 5분 더 저으며 끓인다.']},
 {id:'tmd',n:'참치마요 덮밥',c:'일식',t:10,sp:0,q:1,tools:[['rice','micro','pot']],
  ing:{rice:130,tunacan:100,mayo:25,soysauce:10,gim:3,egg:1},
  steps:['참치캔 기름을 따라내고 마요네즈·간장에 버무린다.','따뜻한 밥 위에 얹는다.','계란프라이와 잘게 자른 김을 올린다.']},
 {id:'mpd',n:'마파두부 덮밥',c:'중식',t:20,sp:2,q:1,tools:['pan',['rice','pot','micro']],
  ing:{rice:100,tofu:200,porkground:80,greenonion:20,gochujang:15,oyster:10,starch:8,garlic:5},
  steps:['다짐육을 볶다가 고추장·굴소스·마늘을 넣는다.','물 150ml를 붓고 깍둑 썬 두부를 조심히 넣는다.','전분물로 농도를 잡고 대파를 뿌려 밥에 얹는다.']},
 {id:'ykd',n:'야끼우동',c:'중식',t:20,sp:1,q:1,tools:['pan','knife'],
  ing:{udon:200,cabbage:80,carrot:30,onion:50,oyster:20,soysauce:10,pork:70},
  steps:['우동면을 30초 데쳐 물기를 뺀다.','센 불에 고기와 채소를 볶는다.','면과 굴소스·간장을 넣고 눌러가며 볶는다.']},
 {id:'gbr',n:'계란 볶음밥',c:'중식',t:15,sp:0,q:1,tools:['pan',['rice','pot','micro']],
  ing:{rice:130,egg:2,greenonion:20,oyster:10,oil:12,ham:40},
  steps:['기름에 대파를 볶아 파기름을 낸다.','계란을 스크램블하고 밥을 넣어 흩뜨리며 볶는다.','굴소스를 팬 가장자리에 둘러 향을 낸다.']},
 {id:'sbr',n:'새우 볶음밥',c:'중식',t:18,sp:0,q:1,tools:['pan',['rice','pot','micro']],
  ing:{rice:130,shrimp:80,egg:1,greenonion:20,oyster:10,corn:30,oil:12},
  steps:['새우를 해동해 물기를 없애고 센 불에 굽는다.','계란·밥·옥수수를 넣고 고슬하게 볶는다.','굴소스로 간하고 대파를 마지막에 넣는다.']},
 {id:'tge',n:'토마토 계란 볶음',c:'중식',t:15,sp:0,q:1,tools:['pan',['rice','pot','micro']],
  ing:{rice:100,tomato:200,egg:2,greenonion:15,sugar:5,salt:3,oil:10},
  steps:['계란을 반숙으로 볶아 따로 덜어 둔다.','토마토를 넣고 물이 나올 때까지 볶는다.','설탕·소금으로 간하고 계란을 다시 합쳐 섞는다.']},
 {id:'dkc',n:'두부김치',c:'중식',t:20,sp:2,q:1,tools:['pan','pot'],
  ing:{tofu:200,kimchi:150,pork:80,sesameoil:8,sugar:5,greenonion:15},
  steps:['두부를 8분 데치거나 팬에 지진다.','고기를 볶다가 김치를 넣고 설탕을 조금 넣어 볶는다.','참기름을 두르고 두부를 둘러 담는다.']},
 {id:'tds',n:'닭가슴살 데리야끼 덮밥',c:'일식',t:20,sp:0,q:1,tools:['pan',['rice','pot']],
  ing:{rice:130,chickenbreast:180,soysauce:20,sugar:10,mirin:15,onion:50,egg:1},
  steps:['닭가슴살을 도톰하게 저며 팬에 굽는다.','간장·설탕·맛술을 넣고 양파와 함께 조린다.','밥에 얹고 반숙 계란을 올린다.']}
];

/* ─────────────────────────  지역과 마트  ───────────────────────── */
const MART = {
  emart:{n:'이마트',f:1.00,p:1.00,note:'대형마트'},
  homeplus:{n:'홈플러스',f:0.99,p:0.97,note:'대형마트'},
  lotte:{n:'롯데마트',f:1.01,p:0.99,note:'대형마트'},
  costco:{n:'코스트코',f:0.97,p:0.97,bulk:2,bd:0.86,note:'창고형 매장 · 두 배 용량 단위로 계산'},
  hanaro:{n:'농협 하나로마트',f:0.92,p:1.02,note:'농협 계열 마트'},
  market:{n:'전통시장',f:0.88,p:1.05,note:'재래시장'},
  super:{n:'동네 슈퍼·편의마트',f:1.10,p:1.12,note:'동네 소형 매장'},
  online:{n:'온라인 장보기',f:0.98,p:0.95,fee:3000,feeFree:40000,note:'온라인 · 4만원 미만이면 배송비 3,000원으로 가정'}
};
const METRO = ['emart','homeplus','lotte','costco','market','super','online'];
const GYEONGGI = ['emart','homeplus','lotte','costco','hanaro','market','super','online'];
const PROVINCE = ['emart','hanaro','homeplus','market','super','online'];
const REGIONS = [
  {k:['서울'],n:'서울',m:METRO},{k:['부산'],n:'부산',m:METRO},{k:['대구'],n:'대구',m:METRO},
  {k:['인천'],n:'인천',m:METRO},{k:['광주'],n:'광주',m:METRO},{k:['대전'],n:'대전',m:METRO},
  {k:['울산'],n:'울산',m:METRO},{k:['세종'],n:'세종',m:GYEONGGI},
  {k:['경기','경기도','수원','성남','고양','용인','부천','안산','안양','화성','평택','의정부','파주','김포','광명','시흥','남양주'],n:'경기',m:GYEONGGI},
  {k:['강원','강원도','강원특별자치도','춘천','원주','강릉','속초'],n:'강원',m:PROVINCE},
  {k:['충북','충청북도','청주','충주','제천'],n:'충북',m:PROVINCE},
  {k:['충남','충청남도','천안','아산','서산','당진'],n:'충남',m:PROVINCE},
  {k:['전북','전라북도','전북특별자치도','전주','익산','군산'],n:'전북',m:PROVINCE},
  {k:['전남','전라남도','여수','순천','목포','광양'],n:'전남',m:PROVINCE},
  {k:['경북','경상북도','포항','구미','경주','안동'],n:'경북',m:PROVINCE},
  {k:['경남','경상남도','창원','김해','진주','양산','거제'],n:'경남',m:PROVINCE},
  {k:['제주','서귀포'],n:'제주',m:['emart','hanaro','market','super','online'],island:true}
];

export { ING, AISLES, FRESH_AISLES, TOOLS, CUISINES, PANTRY, R, MART, REGIONS, PROVINCE };
